# Generated by Django 3.0.5 on 2020-05-28 06:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('num', models.AutoField(primary_key=True, serialize=False)),
                ('roadaddress', models.CharField(blank=True, db_column='roadAddress', max_length=100, null=True, unique=True)),
            ],
            options={
                'db_table': 'address',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Around',
            fields=[
                ('num', models.AutoField(primary_key=True, serialize=False)),
                ('address', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('trans', models.IntegerField(blank=True, null=True)),
                ('comforts', models.IntegerField(blank=True, null=True)),
                ('education', models.IntegerField(blank=True, null=True)),
                ('medical', models.IntegerField(blank=True, null=True)),
                ('eatery', models.IntegerField(blank=True, null=True)),
                ('culture', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'around',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Building',
            fields=[
                ('num', models.AutoField(primary_key=True, serialize=False)),
                ('address', models.CharField(blank=True, max_length=100, null=True)),
                ('sd', models.CharField(blank=True, max_length=20, null=True)),
                ('sgg', models.CharField(blank=True, max_length=20, null=True)),
                ('emd', models.CharField(blank=True, max_length=20, null=True)),
                ('latitude', models.CharField(blank=True, max_length=45, null=True)),
                ('longitude', models.CharField(blank=True, max_length=45, null=True)),
                ('exclusive', models.CharField(blank=True, max_length=10, null=True)),
                ('floor', models.CharField(blank=True, max_length=10, null=True)),
                ('ho', models.CharField(blank=True, max_length=10, null=True)),
                ('kind', models.CharField(blank=True, max_length=10, null=True)),
                ('detail', models.CharField(blank=True, max_length=10, null=True)),
                ('cost', models.CharField(blank=True, max_length=10, null=True)),
                ('monthly', models.CharField(blank=True, max_length=10, null=True)),
                ('license', models.CharField(blank=True, max_length=45, null=True)),
                ('image', models.CharField(blank=True, max_length=200, null=True)),
                ('contractedat', models.DateField(blank=True, db_column='contractedAt', null=True)),
                ('createdat', models.DateTimeField(blank=True, db_column='createdAt', null=True)),
            ],
            options={
                'db_table': 'building',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('num', models.BigIntegerField(primary_key=True, serialize=False)),
                ('nickname', models.CharField(blank=True, max_length=45, null=True)),
                ('auth', models.CharField(blank=True, max_length=10, null=True)),
                ('phonenum', models.CharField(blank=True, db_column='phoneNum', max_length=20, null=True)),
                ('age', models.IntegerField(blank=True, null=True)),
                ('gender', models.CharField(blank=True, max_length=4, null=True)),
                ('address', models.CharField(blank=True, max_length=100, null=True)),
                ('picture', models.CharField(blank=True, max_length=200, null=True)),
                ('createdat', models.DateTimeField(blank=True, db_column='createdAt', null=True)),
                ('enteredat', models.DateTimeField(blank=True, db_column='enteredAt', null=True)),
            ],
            options={
                'db_table': 'user',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Agent',
            fields=[
                ('num', models.OneToOneField(db_column='num', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='api.User')),
                ('name', models.CharField(blank=True, max_length=45, null=True)),
                ('representative', models.CharField(blank=True, max_length=45, null=True)),
                ('license', models.CharField(blank=True, max_length=45, null=True)),
                ('address', models.CharField(blank=True, max_length=100, null=True)),
                ('picture', models.CharField(blank=True, max_length=200, null=True)),
                ('phonenum', models.CharField(blank=True, db_column='phoneNum', max_length=20, null=True)),
                ('count', models.IntegerField(blank=True, null=True)),
                ('point', models.IntegerField(blank=True, null=True)),
                ('delflag', models.IntegerField(blank=True, null=True)),
                ('createdat', models.DateTimeField(blank=True, db_column='createdAt', null=True)),
            ],
            options={
                'db_table': 'agent',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Search',
            fields=[
                ('num', models.OneToOneField(db_column='num', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='api.User')),
                ('keyword', models.CharField(max_length=100)),
                ('date', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'search',
                'managed': False,
            },
        ),
    ]
