# Generated by Django 3.0.5 on 2020-06-03 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Agent',
            fields=[
                ('attention_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('address', models.CharField(blank=True, max_length=255, null=True)),
                ('count', models.IntegerField()),
                ('license', models.CharField(blank=True, max_length=255, null=True)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('phone_num', models.CharField(blank=True, max_length=255, null=True)),
                ('picture', models.CharField(blank=True, max_length=255, null=True)),
                ('point', models.IntegerField()),
                ('representative', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'agent',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Around',
            fields=[
                ('around_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('address', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('trans', models.IntegerField(blank=True, null=True)),
                ('comforts', models.IntegerField(blank=True, null=True)),
                ('education', models.IntegerField(blank=True, null=True)),
                ('medical', models.IntegerField(blank=True, null=True)),
                ('eatery', models.IntegerField(blank=True, null=True)),
                ('culture', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'around',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('contract_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('address', models.CharField(blank=True, max_length=100, null=True)),
                ('sd', models.CharField(blank=True, max_length=20, null=True)),
                ('sgg', models.CharField(blank=True, max_length=20, null=True)),
                ('emd', models.CharField(blank=True, max_length=20, null=True)),
                ('latitude', models.CharField(blank=True, max_length=45, null=True)),
                ('longitude', models.CharField(blank=True, max_length=45, null=True)),
                ('exclusive', models.CharField(blank=True, max_length=10, null=True)),
                ('floor', models.CharField(blank=True, max_length=10, null=True)),
                ('ho', models.CharField(blank=True, max_length=10, null=True)),
                ('kind', models.CharField(blank=True, max_length=10, null=True)),
                ('detail', models.CharField(blank=True, max_length=10, null=True)),
                ('cost', models.BigIntegerField(blank=True, null=True)),
                ('monthly', models.CharField(blank=True, max_length=10, null=True)),
                ('license', models.CharField(blank=True, max_length=45, null=True)),
                ('image', models.CharField(blank=True, max_length=200, null=True)),
                ('contract_date', models.DateField(blank=True, null=True)),
            ],
            options={
                'db_table': 'contract',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Favorite',
            fields=[
                ('num', models.AutoField(primary_key=True, serialize=False)),
                ('score', models.IntegerField()),
            ],
            options={
                'db_table': 'favorite',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Interest',
            fields=[
                ('interest_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('birth', models.IntegerField(blank=True, max_length=255, null=True)),
                ('first', models.CharField(blank=True, max_length=255, null=True)),
                ('gender', models.CharField(blank=True, max_length=255, null=True)),
                ('sd', models.CharField(blank=True, max_length=255, null=True)),
                ('second', models.CharField(blank=True, max_length=255, null=True)),
                ('sgg', models.CharField(blank=True, max_length=255, null=True)),
                ('third', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'interest',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Search',
            fields=[
                ('search_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('keyword', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'search',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('status_id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('address', models.CharField(blank=True, max_length=100, null=True)),
                ('sd', models.CharField(blank=True, max_length=20, null=True)),
                ('sgg', models.CharField(blank=True, max_length=20, null=True)),
                ('emd', models.CharField(blank=True, max_length=20, null=True)),
                ('latitude', models.CharField(blank=True, max_length=45, null=True)),
                ('longitude', models.CharField(blank=True, max_length=45, null=True)),
                ('exclusive', models.CharField(blank=True, max_length=10, null=True)),
                ('floor', models.CharField(blank=True, max_length=10, null=True)),
                ('ho', models.CharField(blank=True, max_length=10, null=True)),
                ('category', models.CharField(blank=True, max_length=10, null=True)),
                ('detail', models.CharField(blank=True, max_length=10, null=True)),
                ('cost', models.BigIntegerField(blank=True, null=True)),
                ('license', models.CharField(blank=True, max_length=45, null=True)),
                ('image', models.CharField(blank=True, max_length=200, null=True)),
                ('report_date', models.DateField(blank=True, null=True)),
            ],
            options={
                'db_table': 'status',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('num', models.BigIntegerField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('auth', models.CharField(blank=True, max_length=255, null=True)),
                ('nickname', models.CharField(blank=True, max_length=255, null=True)),
                ('picture', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'user',
                'managed': False,
            },
        ),
    ]
