# Generated by Django 3.0.5 on 2020-06-11 07:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Status',
        ),
    ]
